import Foundation
import UIKit

/// The sheet other races ask for.
///
/// Entering a qualifier or a championship slot usually means proving you have
/// finished something, and the proof wanted is always the same five columns:
/// date, race, bib, official time, division place. Athletes assemble it by hand
/// from a dozen results pages. This assembles it from the locker.
enum ResumeBuilder {
    struct Options {
        var kinds: Set<RaceKind>
        var includeSplits: Bool
        var includeDNF: Bool

        static let `default` = Options(kinds: Set(RaceKind.allCases), includeSplits: true, includeDNF: false)
    }

    static func rows(for results: [RaceResult], options: Options) -> [RaceResult] {
        results
            .filter { options.kinds.contains($0.kind) }
            .filter { options.includeDNF ? !$0.didNotStart : $0.isComplete }
            .sortedByDateDescending()
    }

    static func plainText(athlete: Athlete, results: [RaceResult], options: Options = .default) -> String {
        let rows = rows(for: results, options: options)
        let summary = RaceAnalytics.summary(rows)
        var lines: [String] = []
        lines.append("RACE RESUME: \(athlete.name.uppercased())")
        if let location = athlete.location {
            lines.append(location)
        }
        if let years = summary.years {
            lines.append("\(summary.finishes) finishes, \(years.lowerBound)–\(years.upperBound)")
        }
        lines.append("")

        for result in rows {
            var line = "\(dateText(result))  \(result.raceName)"
            if let bib = result.bib { line += "  ·  Bib \(bib)" }
            lines.append(line)
            var detail = "    \(result.kind.longTitle)  ·  \(TimeFormat.hms(result.finish))"
            if let group = result.ageGroup { detail += "  ·  \(group)" }
            if let place = result.finishRankGroup { detail += " #\(place)" }
            if let overall = result.finishRankOverall { detail += "  ·  \(overall) overall" }
            if !result.isComplete { detail += "  ·  DNF" }
            lines.append(detail)
            if options.includeSplits, result.isComplete {
                let splits = [Discipline.swim, .t1, .bike, .t2, .run]
                    .compactMap { leg -> String? in
                        guard let seconds = result.seconds(for: leg), seconds > 0 else { return nil }
                        return "\(leg.title) \(TimeFormat.hms(seconds))"
                    }
                if !splits.isEmpty {
                    lines.append("    " + splits.joined(separator: "  ·  "))
                }
            }
            lines.append("")
        }
        lines.append("Generated by IM Iron Splits. Times as published by the event timer.")
        return lines.joined(separator: "\n")
    }

    /// A one-column PDF of the same content, for the forms that want a file.
    static func pdf(athlete: Athlete, results: [RaceResult], options: Options = .default) -> URL? {
        let text = plainText(athlete: athlete, results: results, options: options)
        let pageSize = CGSize(width: 612, height: 792)   // US Letter at 72 dpi
        let margin: CGFloat = 48
        let bodyFont = UIFont.monospacedSystemFont(ofSize: 9.5, weight: .regular)
        let attributes: [NSAttributedString.Key: Any] = [
            .font: bodyFont,
            .foregroundColor: UIColor.black,
        ]
        let attributed = NSAttributedString(string: text, attributes: attributes)

        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(origin: .zero, size: pageSize))
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(fileSafe(athlete.name))-race-resume.pdf")

        // Paginate by hand with CoreText rather than letting the renderer clip:
        // a resume that silently loses its last four races is worse than no
        // resume at all, and these run to several pages for anyone with a
        // history worth exporting.
        let framesetter = CTFramesetterCreateWithAttributedString(attributed)
        let textRect = CGRect(x: margin, y: margin, width: pageSize.width - margin * 2, height: pageSize.height - margin * 2)
        let path = CGPath(rect: textRect, transform: nil)

        do {
            try renderer.writePDF(to: url) { context in
                var location = 0
                repeat {
                    context.beginPage()
                    guard let cgContext = UIGraphicsGetCurrentContext() else { return }
                    cgContext.textMatrix = .identity
                    cgContext.translateBy(x: 0, y: pageSize.height)
                    cgContext.scaleBy(x: 1, y: -1)

                    let frame = CTFramesetterCreateFrame(framesetter, CFRangeMake(location, 0), path, nil)
                    CTFrameDraw(frame, cgContext)
                    let visible = CTFrameGetVisibleStringRange(frame)
                    guard visible.length > 0 else { return }
                    location += visible.length
                } while location < attributed.length
            }
            return url
        } catch {
            return nil
        }
    }

    /// ISO date, so the resume sorts and reads the same in every locale it is
    /// sent to. Formatted from calendar components because `DateFormatter` is
    /// not `Sendable` and this runs off the main actor.
    private static func dateText(_ result: RaceResult) -> String {
        guard let date = result.eventDate else {
            return result.year > 0 ? String(result.year) : "Undated"
        }
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = TimeZone(secondsFromGMT: 0) ?? .gmt
        let parts = calendar.dateComponents([.year, .month, .day], from: date)
        return String(format: "%04d-%02d-%02d", parts.year ?? 0, parts.month ?? 0, parts.day ?? 0)
    }

    private static func fileSafe(_ name: String) -> String {
        name.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .filter { !$0.isEmpty }
            .joined(separator: "-")
    }
}
